### ISSUE TITLE
Automated test of tutorials

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#3]
The tutorials are all written as jupyter notebooks. A GitHub action should be created, that extracts the python code and runs it. If the code can't be executed without errors, the action should fail. This way we ensure that the tutorials are up-to-date.

A possible approach might be to automatically create a `test_`-file which contains a `test_` function for each notebook. Each of those functions just executes the extracted code which is stored in a separate file for each notebook. Have a look at this link: [click me](https://stackoverflow.com/questions/3781851/run-a-python-script-from-another-python-script-passing-in-arguments)

## tasks
- [ ] Create Github action
- [ ] Create a script, that extracts the code from all jupyter notebooks
- [ ] Run the code and ensure that an error causes the Github action to fail

**Comment by CagtayFabry** [comment]
@vhirtham maybe we can look at using [nbsphinx ](https://nbsphinx.readthedocs.io)for this as well (probably need to implement this anyway)

Error handling should fail the docs build in this case:
https://nbsphinx.readthedocs.io/en/0.6.0/allow-errors.html

**Comment by CagtayFabry** [comment]
closed with #124
