### ISSUE TITLE
Time class todos

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#445]
We have merged a first version of the `Time` class and skipped some things that aren't that important for now. But we should still implement them before the 0.5.0 release:

-  [x] Use a [descriptor](https://docs.python.org/3/howto/descriptor.html) for the `union` method to use it as class and instance method. See [this link](https://stackoverflow.com/questions/28237955/same-name-for-classmethod-and-instancemethod/28238212#28238212)
- [x] implement `__repr__` function
- [x] Check docstrings if something is missing
- [x] ~~Tutorial~~ dropped for now
- [x] Add test for `+` operator if `Time` instance represents an absolute time --- basically copy-paste the already existing test for a time delta `Time`, remove absolute types for the `other` object and tweak the expected results.
- [x] move time related utility functions to `time.py`
- [x] Test `-` operator
- [x] Test `union`
- [x] Reevaluate comments in PR #440
- [x] Reevaluate comments in PR #448

Since all the accessors will already by used all over the place, we probably don't need dedicated tests for them
